"""Add technical specification columns to Laptop

Revision ID: 2399ba541020
Revises: c55bd301e31e
Create Date: 2026-02-09 18:01:58.713867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2399ba541020'
down_revision = 'c55bd301e31e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_family', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('processor_generation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('processor_model', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('npu', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_column('npu')
        batch_op.drop_column('processor_model')
        batch_op.drop_column('processor_generation')
        batch_op.drop_column('processor_family')

    # ### end Alembic commands ###
