"""Sync processor fields

Revision ID: 3f71fa9d00ae
Revises: 497434710d0a
Create Date: 2026-02-08 12:22:32.253010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f71fa9d00ae'
down_revision = '497434710d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_laptops_processor_family'), ['processor_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_generation'), ['processor_generation'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_model_number'), ['processor_model_number'], unique=False)

    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('model_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.drop_column('model_number')
        batch_op.drop_column('generation')

    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_laptops_processor_model_number'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_generation'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_family'))

    # ### end Alembic commands ###
