"""add component full names

Revision ID: 854478d0d9b3
Revises: 2399ba541020
Create Date: 2026-02-09 18:16:36.380456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854478d0d9b3'
down_revision = '2399ba541020'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graphics_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discrete_full_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('onboard_full_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('operating_systems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('ram', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('screens', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('ram', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('processors', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('operating_systems', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    with op.batch_alter_table('graphics_cards', schema=None) as batch_op:
        batch_op.drop_column('onboard_full_name')
        batch_op.drop_column('discrete_full_name')

    # ### end Alembic commands ###
