"""Add keyboard and biometric fields

Revision ID: c55bd301e31e
Revises: eccd589777e5
Create Date: 2026-02-09 16:46:24.184278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c55bd301e31e'
down_revision = 'eccd589777e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numeric_keypad', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('keyboard_language', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('pointing_device', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('keyboard_backlight_color', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('keyboard_backlight_zone', sa.String(length=50), nullable=True))
        batch_op.drop_column('keyboard_numeric_pad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('keyboard_numeric_pad', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('keyboard_backlight_zone')
        batch_op.drop_column('keyboard_backlight_color')
        batch_op.drop_column('pointing_device')
        batch_op.drop_column('keyboard_language')
        batch_op.drop_column('numeric_keypad')

    # ### end Alembic commands ###
