"""normalize_laptop_specs

Revision ID: eccd589777e5
Revises: 3f71fa9d00ae
Create Date: 2026-02-08 21:10:53.495770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eccd589777e5'
down_revision = '3f71fa9d00ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_lbs', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('touchscreen_override', sa.Boolean(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_laptop_gpu'))
        batch_op.drop_index(batch_op.f('idx_laptop_screen'))
        batch_op.drop_index(batch_op.f('idx_laptop_specs'))
        batch_op.drop_index(batch_op.f('ix_laptops_has_discrete_gpu'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_family'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_full_name'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_generation'))
        batch_op.drop_index(batch_op.f('ix_laptops_processor_model_number'))
        batch_op.drop_index(batch_op.f('ix_laptops_ram_capacity'))
        batch_op.drop_index(batch_op.f('ix_laptops_screen_size'))
        batch_op.drop_index(batch_op.f('ix_laptops_storage_capacity'))
        batch_op.drop_column('npu')
        batch_op.drop_column('processor_family')
        batch_op.drop_column('touchscreen')
        batch_op.drop_column('ram_capacity')
        batch_op.drop_column('processor_generation')
        batch_op.drop_column('processor_full_name')
        batch_op.drop_column('storage_capacity')
        batch_op.drop_column('has_discrete_gpu')
        batch_op.drop_column('screen_size')
        batch_op.drop_column('processor_model_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laptops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processor_model_number', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('screen_size', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('has_discrete_gpu', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('storage_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processor_full_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processor_generation', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ram_capacity', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('touchscreen', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('processor_family', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('npu', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.create_index(batch_op.f('ix_laptops_storage_capacity'), ['storage_capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_screen_size'), ['screen_size'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_ram_capacity'), ['ram_capacity'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_model_number'), ['processor_model_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_generation'), ['processor_generation'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_full_name'), ['processor_full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_processor_family'), ['processor_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_laptops_has_discrete_gpu'), ['has_discrete_gpu'], unique=False)
        batch_op.create_index(batch_op.f('idx_laptop_specs'), ['processor_full_name', 'ram_capacity', 'storage_capacity'], unique=False)
        batch_op.create_index(batch_op.f('idx_laptop_screen'), ['screen_size'], unique=False)
        batch_op.create_index(batch_op.f('idx_laptop_gpu'), ['has_discrete_gpu'], unique=False)
        batch_op.drop_column('touchscreen_override')
        batch_op.drop_column('weight_lbs')

    # ### end Alembic commands ###
